# Generated by Django 3.0.5 on 2020-06-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rating',
            field=models.IntegerField(),
        ),
    ]
