##File Name : D:\Python4\test.py
sid = input("Student Id : ")
sname = input("Student Name : ")
sage = int(input("Student Age : "))
squal = eval(input("Student Qualifications in List : "))
ssubjects = eval(input("Student Subjects in Tuple : "))
stechs = eval(input("Student Technologies in set : "))
ssubjects_and_marks = eval(input("Student Subjects and Marks in Dict :"))

print()
print("Student Details")
print("----------------------")
print("Student Id :",sid)
print("Student Name :",sname)
print("Student Age :",sage)
print("Student Qual :",squal)
print("Student Subjects :",ssubjects)
print("Student Techs :",stechs)
print("Student Subjects and Marks :",ssubjects_and_marks)
