#from builtins import print

print(5555)

a="sagar,its single line str data type"
c='chiku, its single line str data type'
d='''this is multiline string data
hello world '''
e="sachin is a 'indian' player"
f= 'sachin is a "indian" player' #

h=40            #it is int type data
g=40.0          # it is float type data   
print(a)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)


_id=55
id(_id)